---
collections:
  - name: community.general
    source: https://production-aap.apps.ocp.bk.lab/api/galaxy/content/community/
  - name: servicenow.itsm
    source: https://production-aap.apps.ocp.bk.lab/api/galaxy/content/rh-certified/
