---
version: 3

images:
  base_image:
    name: registry.redhat.io/ubi9/ubi:latest

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-c -v"

dependencies:
  python_interpreter:
    package_system: "python3.11"
    python_path: "/usr/bin/python3.11"
  ansible_core:
    package_pip: ansible-core~=2.18,<2.19
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  system: bindep.txt

additional_build_files:
  - src: files/ansible.cfg
    dest: configs

additional_build_steps:
  prepend_builder:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.19-for-rhel-9-x86_64-rpms.enabled=true"
  prepend_final:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.19-for-rhel-9-x86_64-rpms.enabled=true"
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
  append_final:
    - RUN rm -f /etc/ansible/ansible.cfg

options:
  package_manager_path: /usr/bin/dnf

