---
version: 3

images:
  base_image:
    name: registry.redhat.io/ubi9/ubi:latest

dependencies:
  python_interpreter:
    package_system: "python3.11"
    python_path: "/usr/bin/python3.11"
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  system: bindep.txt

additional_build_files:
  - src: files/ansible.cfg
    dest: configs
  - src: files/bklabca.pem
    dest: certs

additional_build_steps:
  # prepend_base:
  #  - RUN $PYCMD -m pip install wheel
  prepend_builder:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.18-for-rhel-9-x86_64-rpms.enabled=true"
  prepend_final:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.18-for-rhel-9-x86_64-rpms.enabled=true"
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - ADD _build/certs/bklabca.pem /etc/pki/ca-trust/source/anchors/bklabca.pem
    - RUN update-ca-trust
  append_final:
    - RUN rm -f /etc/ansible/ansible.cfg

options:
  package_manager_path: /usr/bin/dnf

