---
collections:
  - name: kubernetes.core
    version: 6.3.0
    source: https://production-aap.apps.ocp.bk.lab/api/galaxy/content/rh-certified/
  - name: redhat.openshift
    source: https://production-aap.apps.ocp.bk.lab/api/galaxy/content/rh-certified/
  - name: redhat.openshift_virtualization
    source: https://production-aap.apps.ocp.bk.lab/api/galaxy/content/rh-certified/
