---
version: 3

images:
  base_image:
    name: registry.redhat.io/ubi9/ubi:latest

options:
  package_manager_path: /usr/bin/dnf

dependencies:
  python_interpreter:
    package_system: "python3.12"
    python_path: "/usr/bin/python3.12"
  ansible_core:
    package_pip: ansible-core~=2.18,<2.19
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-c -v"
  PKGMGR_PRESERVE_CACHE: "always"

additional_build_files:
  - src: files/ansible.cfg
    dest: configs

additional_build_steps:
  prepend_builder:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.18-for-rhel-9-x86_64-rpms.enabled=true"
  prepend_final:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.18-for-rhel-9-x86_64-rpms.enabled=true"
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
  append_final:
    - RUN rm -f /etc/ansible/ansible.cfg
    - RUN rm -f /etc/pki/ca-trust/source/anchors/bklabca.pem
    - RUN update-ca-trust
...

