---
version: 3

images:
  base_image:
    name: registry.redhat.io/ubi9/ubi:latest

options:
  package_manager_path: /usr/bin/dnf

dependencies:
  python_interpreter:
    package_system: "python3.11"
    python_path: "/usr/bin/python3.11"
  ansible_core:
    package_pip: ansible-core==2.16.14
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "--pre -c -v"
  PKGMGR_PRESERVE_CACHE: "always"

additional_build_files:
  - src: files/ansible.cfg
    dest: configs
  - src: files/bklabca.pem
    dest: certs

additional_build_steps:
  prepend_builder:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=ansible-automation-platform-2.5-for-rhel-9-x86_64-rpms.enabled=true"
  prepend_final:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=ansible-automation-platform-2.5-for-rhel-9-x86_64-rpms.enabled=true"
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - ADD _build/certs/bklabca.pem /etc/pki/ca-trust/source/anchors/bklabca.pem
    - RUN update-ca-trust
  append_final:
    - RUN rm -f /etc/ansible/ansible.cfg
...

