---
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.windows
  - name: community.windows
  - name: redhat.insights
  - name: redhat.rhel_idm
  - name: redhat.rhel_system_roles
  - name: redhat.satellite
  - name: redhat.satellite_operations
