---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "--pre -c -v"
  PKGMGR_PRESERVE_CACHE: "always"

dependencies:
  python_interpreter:
    package_system: "python3.11"
    python_path: "/usr/bin/python3.11"
  ansible_core:
    package_pip: ansible-core~=2.18,<2.19
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

images:
  base_image:
    name: registry.redhat.io/ubi9/ubi:latest

options:
  package_manager_path: /usr/bin/dnf

additional_build_files:
  - src: files/ansible.cfg
    dest: configs
  - src: files/bklabca.pem
    dest: certs

additional_build_steps:
  append_base: |
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - ADD _build/certs/bklabca.pem /etc/pki/ca-trust/source/anchors/bklabca.pem
    - RUN update-ca-trust
  append_final:
    - RUN rm -f /etc/ansible/ansible.cfg
...
